version: "3.4"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_backend_test
    # Mount and run tests.
    volumes:
      - ./tests:/tests
    command: ["sh", "-c", "npm run test:api"]
